model:
  filters: 8
  kernel: 3
  k_pool: 2
  pool: "max"
  n_cov: 4
  n_dcov: 4
  act: "swish"
  img_size: 384
hyper:
  batch_size: 4
  loss: 5.0
  masking: "../../processed_data/PR/Probe/mask_probe_384_AuNP.npy"
  probe: "../../processed_data/PR/Probe/probe_function_384_AuNP.npy"
  probe_mode: "multi_c"
  n_refine: 5
  n_time: 5
  sample: "aunp"
  dist: True
  lr: 0.001
  probe_norm: 1.0
  save_path: "trained_models/public/AuNP_exp_1s_384"
  train_data: "../../processed_data/PR/AuNp_expdata/frameimg_exposure_1s.npz"
